export const FORM_VALIDATE = 'FORM_VALIDATE';
export const FORM_VALIDATE_SUCCESS = 'FORM_VALIDATE_SUCCESS';
export const FORM_VALIDATE_ERROR = 'FORM_VALIDATE_ERROR';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const START_PRODUCTS_DOWNLOAD = 'START_PRODUCTS_DOWNLOAD';
export const PRODUCTS_DOWNLOAD_SUCCESS = 'PRODUCTS_DOWNLOAD_SUCCESS';
export const PRODUCTS_DOWNLOAD_ERROR = 'PRODUCTS_DOWNLOAD_ERROR';

export const GET_DELETE_PRODUCT = 'GET_DELETE_PRODUCT';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR';

export const GET_EDIT_PRODUCT = 'GET_EDIT_PRODUCT';
export const GET_EDIT_PRODUCT_SUCCESS = 'GET_EDIT_PRODUCT_SUCCESS';
export const GET_EDIT_PRODUCT_ERROR = 'GET_EDIT_PRODUCT_ERROR';

export const START_EDITION_PRODUCT = 'START_EDITION_PRODUCT';
export const START_EDITION_PRODUCT_SUCCESS = 'START_EDITION_PRODUCT_SUCCESS';
export const START_EDITION_PRODUCT_ERROR = 'START_EDITION_PRODUCT_ERROR';
